# Beer Profile and Rating Dataset

## 1. Basic information
This data set contains tasting profiles and consumer reviews for 3197 unique beers from 934 different breweries. The data was collected from Kaggle: 
https://www.kaggle.com/datasets/ruthgn/beer-profile-and-ratings-data-set?resource=download

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df_beer = pd.read_csv('beer_profile_and_ratings.csv')
df_beer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3197 entries, 0 to 3196
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               3197 non-null   object
 1   Style              3197 non-null   object
 2   Brewery            3197 non-null   object
 3   Beer Name (Full)   3197 non-null   object
 4   Description        3197 non-null   object
 5   ABV                3197 non-null   float64
 6   Min IBU            3197 non-null   int64
 7   Max IBU            3197 non-null   int64
 8   Astringency        3197 non-null   int64
 9   Body               3197 non-null   int64
 10  Alcohol            3197 non-null   int64
 11  Bitter             3197 non-null   int64
 12  Sweet              3197 non-null   int64
 13  Sour               3197 non-null   int64
 14  Salty              3197 non-null   int64
 15  Fruits             3197 non-null   int64
 16  Hoppy              3197 non-null   int64
 17  Spices             3197 non-null   int64
 18  Malty              3197 non-null   int64
 19  review_aroma       3197 non-null   float64
 20  review_appearance  3197 non-null   float64
 21  review_palate      3197 non-null   float64
 22  review_taste       3197 non-null   float64
 23  review_overall     3197 non-null   float64
 24  number_of_reviews  3197 non-null   int64
dtypes: float64(6), int64(14), object(5)
memory usage: 624.5+ KB

In [7]:
df_beer.columns

Index(['Name', 'Style', 'Brewery', 'Beer Name (Full)', 'Description', 'ABV',
       'Min IBU', 'Max IBU', 'Astringency', 'Body', 'Alcohol', 'Bitter',
       'Sweet', 'Sour', 'Salty', 'Fruits', 'Hoppy', 'Spices', 'Malty',
       'review_aroma', 'review_appearance', 'review_palate', 'review_taste',
       'review_overall', 'number_of_reviews'],
      dtype='object')

## 2. Contents of the dataset

## Beer Profile and Ratings Dataset Documentation

This dataset integrates basic beer metadata, sensory profile features derived from review texts, and aggregated user ratings.

---

## Main Dataset: `beer_profile_and_ratings.csv` (`df_beer`)

The dataset consists of 25 columns, categorized into three primary groups:

### 1. Basic Information
| No. | Column Name | Description |
| :--- | :--- | :--- |
| 1 | **Name** | Beer name (Label) |
| 2 | **Style** | Beer Style |
| 3 | **Brewery** | Brewery name |
| 4 | **Beer Name (Full)** | Complete beer name (Brewery + Brew Name) — **Unique Identifier** |
| 5 | **Description** | Notes on the beer (if available) |
| 6 | **ABV** | Alcohol content by volume (%) |
| 7 | **Min IBU** | Minimum IBU value for the specific beer style |
| 8 | **Max IBU** | Maximum IBU value for the specific beer style |

### 2. Tasting Profile Features
*Note: These features represent word counts extracted from up to 25 reviews per beer. They quantify the presence of specific descriptors mentioned by reviewers.*

* **Mouthfeel:**
    * `Astringency`, `Body`, `Alcohol`
* **Taste:**
    * `Bitter`, `Sweet`, `Sour`, `Salty`
* **Flavor and Aroma:**
    * `Fruits`, `Hoppy`, `Spices`, `Malty`

### 3. Review and Rating Metrics (higher values indicate more positive reviews)
| No. | Column Name | Description |
| :--- | :--- | :--- |
| 20 | **review_aroma** | Average score for aroma |
| 21 | **review_appearance** | Average score for appearance |
| 22 | **review_palate** | Average score for palate |
| 23 | **review_taste** | Average score for taste |
| 24 | **review_overall** | Average overall rating score |
| 25 | **number_of_reviews** | Total count of consumer/user reviews |

---

In [9]:
df_beer.head()

,Name,Style,Brewery,Beer Name (Full),Description,ABV,Min IBU,Max IBU,Astringency,Body,...,Fruits,Hoppy,Spices,Malty,review_aroma,review_appearance,review_palate,review_taste,review_overall,number_of_reviews
0,Amber,Altbier,Alaskan Brewing Co.,Alaskan Brewing Co. Alaskan Amber,"Notes:Richly malty and long on the palate, wit...",5.3,25,50,13,32,...,33,57,8,111,3.498994,3.636821,3.556338,3.643863,3.847082,497
1,Double Bag,Altbier,Long Trail Brewing Co.,Long Trail Brewing Co. Double Bag,"Notes:This malty, full-bodied double alt is al...",7.2,25,50,12,57,...,24,35,12,84,3.798337,3.846154,3.904366,4.024948,4.034304,481
2,Long Trail Ale,Altbier,Long Trail Brewing Co.,Long Trail Brewing Co. Long Trail Ale,Notes:Long Trail Ale is a full-bodied amber al...,5.0,25,50,14,37,...,10,54,4,62,3.409814,3.667109,3.600796,3.631300,3.830239,377
3,Doppelsticke,Altbier,Uerige Obergärige Hausbrauerei GmbH / Zum Uerige,Uerige Obergärige Hausbrauerei GmbH / Zum Ueri...,Notes:,8.5,25,50,13,55,...,49,40,16,119,4.148098,4.033967,4.150815,4.205163,4.005435,368
4,Sleigh'r Dark Doüble Alt Ale,Altbier,Ninkasi Brewing Company,Ninkasi Brewing Company Sleigh'r Dark Doüble A...,Notes:Called 'Dark Double Alt' on the label.Se...,7.2,25,50,25,51,...,11,51,20,95,3.625000,3.973958,3.734375,3.765625,3.817708,96

## 3. Statistical Summary:

In general, the dataset has 3197 rows and 25 columns. We have the categorical colums and numerical columns. The large part of columns are numerical, only the name, style, brewery and description are categorical.

#### 1. Categorical Features (Group & Filter)

* **Identifiers:** `Name`, `Beer Name (Full)`, `Brewery`
* **Descriptors:** `Style`, `Description`

#### 2. Numerical Features (Quantitative Analysis)


| Category | Column Names |
| :--- | :--- |
| **Specifications** | `ABV`, `Min IBU`, `Max IBU` |
| **Profile Intensity** | `Astringency`, `Body`, `Alcohol` (Mouthfeel); `Bitter`, `Sweet`, `Sour`, `Salty` (Taste); `Fruits`, `Hoppy`, `Spices`, `Malty` (Flavor) |
| **User Ratings** | `review_aroma`, `review_appearance`, `review_palate`, `review_taste`, `review_overall` |
| **Volume Metrics** | `number_of_reviews` |

---
**Note:** All Rating columns are on a 1–5 scale (Higher = Better). `number_of_reviews` should be used to calculate weighted averages if necessary.

#### Details of numerical features:

In [18]:
specific_cols = ['ABV', 'Min IBU', 'Max IBU']
df_beer[specific_cols].describe().round(2)

           ABV  Min IBU  Max IBU
count  3197.00  3197.00  3197.00
mean      6.53    21.18    38.99
std       2.55    13.24    21.36
min       0.00     0.00     0.00
25%       5.00    15.00    25.00
50%       6.00    20.00    35.00
75%       7.60    25.00    45.00
max      57.50    65.00   100.00

In [19]:
profile_features = [
    'Astringency', 'Body', 'Alcohol',           # Mouthfeel
    'Bitter', 'Sweet', 'Sour', 'Salty',         # Taste
    'Fruits', 'Hoppy', 'Spices', 'Malty'        # Flavor/Aroma
]

df_beer[profile_features].describe().round(2)

,Astringency,Body,Alcohol,Bitter,Sweet,Sour,Salty,Fruits,Hoppy,Spices,Malty
count,3197.00,3197.00,3197.00,3197.00,3197.00,3197.00,3197.00,3197.00,3197.00,3197.00,3197.00
mean,16.52,46.13,17.06,36.36,58.27,33.15,1.02,38.53,40.92,18.35,75.33
std,10.41,25.95,17.33,25.79,34.28,35.78,2.13,32.30,30.40,23.76,39.91
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,9.00,29.00,6.00,17.00,33.00,11.00,0.00,12.00,18.00,4.00,45.00
50%,14.00,40.00,11.00,31.00,54.00,22.00,0.00,29.00,33.00,10.00,73.00
75%,21.00,58.00,22.00,52.00,77.00,42.00,1.00,60.00,56.00,23.00,103.00
max,81.00,175.00,139.00,150.00,263.00,284.00,48.00,175.00,172.00,184.00,239.00

In [20]:
rating_features = [
    'review_aroma', 'review_appearance', 'review_palate', 
    'review_taste', 'review_overall'
]
df_beer[rating_features].describe().round(2)

,review_aroma,review_appearance,review_palate,review_taste,review_overall
count,3197.00,3197.00,3197.00,3197.00,3197.00
mean,3.64,3.75,3.66,3.70,3.75
std,0.50,0.40,0.45,0.51,0.44
min,1.51,1.57,1.29,1.21,1.14
25%,3.42,3.60,3.47,3.50,3.57
50%,3.72,3.83,3.74,3.79,3.83
75%,3.98,4.00,3.97,4.03,4.03
max,5.00,4.67,5.00,5.00,5.00

In [21]:
volume_features = ['number_of_reviews']
df_beer[volume_features].describe().round(2)

       number_of_reviews
count            3197.00
mean              233.28
std               361.81
min                 1.00
25%                23.00
50%                93.00
75%               284.00
max              3290.00

## 4. Objective of using the dataset

The primary goal of utilizing this dataset is to explore the potential clusters of the beer based on the specifications and the tasting profile features. We will use different clustering algorithms to find the clusters and then compare the clusters with the style of the beer in the dataset. We will also analysis the relationship between the clusters and the ratings of the beer, try to find the clusters that have higher ratings, and try to explain the reason why the beer in these clusters have higher preferences.